### ISSUE TITLE
listResources with all set to true breaks router overriding

### ISSUE THREAD

**Issue by Silic0nS0ldier** [userfrosting/UniformResourceLocator#4]
This problem was introduced by https://github.com/userfrosting/UniformResourceLocator/commit/fc852a1f85ebcabfcd8fa7f60807c9749ef5a2c9 which was likely introduced to facilitate migrations running in the correct order.

There are 2 problems here.

1. Existing sorting is imperfect, core always ends up at the top even when something should stand above it. This means migrations have an edge case.
2. Routes need to sort by sprinkles and then path names to correctly override.

**Comment by lcharette** [comment]
(To keep track of what I wrote on the chat)

I see why the sort now. When not returning all files, the loop will get all files from the lowest priority location (sprinkle), then move to the next location until the topmost, replacing any existing file in the list with one of the highest priority. So core add a file to the list => account replace the file.

Replacement is done here : https://github.com/userfrosting/UniformResourceLocator/blob/master/src/ResourceLocator.php#L393

So in the end, `listResources` is not designed to be sorted by sprinkles... at least when **not** returning all files. The sorting when returning all files is a consequence of this overwriting. 

So 3 solutions:
1. Add a new method which will return the correct order
2. Add an argument to specify which sort we want
3. Change the sort altogether and abandon the sort by file thing

**Comment by lcharette** [comment]
Considering sprinkles `Floor, Floor2, Floor3`, 3 is highest priority and 1 lowest, [the current tests](https://github.com/userfrosting/UniformResourceLocator/blob/f4ae6f1f57f0341de998eb6eeb015179a2551534/tests/BuildingLocatorTest.php#L419-L429) produce an error since the location order is the same as the sort.
```
            $this->getBasePath() . 'Floors/Floor/files/test/blah.json',
            $this->getBasePath() . 'Floors/Floor2/files/data/foo.json',
            $this->getBasePath() . 'Floors/Floor2/files/foo.json',
            $this->getBasePath() . 'Floors/Floor3/files/test.json'
```
Technically, `Floor3` and `Floor` lines should be reversed... 

The same result as above would be encountered if the location priority was reversed, ie. 1 as the highest priority and 3 lowest. Bu in that case, it's what we actually want...
 

This means the tests should be updated to use better naming convention for locations to avoid this edge case...

**Comment by lcharette** [comment]
Went with #2...
